### ISSUE TITLE
Support for reStructuredText and Re:VIEW format

### ISSUE THREAD

**Issue by huideyeren** [1000ch/linter-textlint#31]
Checking does not work while editing reStructuredText or Re:VIEW file.

I hope to be able to use reStructuredText and Re:VIEW files as well.

（It will be helpful if you can communicate in Japanese.）

**Comment by erukiti** [comment]
1. ローカルに textlint や textlint-plugin-review と textlint-rule-* をインストール
2. CLI で textlint を叩くと *.re ファイルを処理可能なのを確認
3. linter-textlintをインストールして、Atom 上で *.txtや*.mdでのtextlint処理可能なのを確認
4. この条件で、*.re が Atom上では無反応です

https://twitter.com/azu_re/status/824788826904145922

https://github.com/1000ch/linter-textlint/blob/e8f4bce03013dc283b057ab718515398432f2ff3/lib/index.js#L45

が怪しそうだというところですが、それ以上はちょっとわかりませんでした。

**Comment by 1000ch** [comment]
@huideyeren @erukiti 
Sorry for delay, this may be fixed on `v2.2.0`. Please try it 🙏
