### ISSUE TITLE
textlint@9

### ISSUE THREAD

**Issue by azu** [1000ch/linter-textlint#39]
Currently, linter-textlint use textlint@^8

- https://github.com/1000ch/linter-textlint/blob/4d8a78f2cf06ad49728612d7d820108e85177f03/package.json#L49

textlint@9 have been released.

- https://github.com/textlint/textlint/releases/tag/textlint%409.0.0

We want to upgrade this.

**Comment by 1000ch** [comment]
[v3.0.0](https://github.com/1000ch/linter-textlint/releases/tag/v3.0.0) released ✅

**Comment by azu** [comment]
@1000ch Thanks!
