### ISSUE TITLE
linter-textlintが全く反応しない

### ISSUE THREAD

**Issue by wate** [1000ch/linter-textlint#6]
下記の環境で利用としても、linter-textlintまったく反応せず、
lintの結果がAtom側に表示されない。
- Atom: 1.0.19
  - linter-textlint: 1.1.0
- OS: OS X El Capitan

.textlintrc

```
{
  "rules": {
    "max-ten": true,
    "spellcheck-tech-word": true,
    "no-mix-dearu-desumasu": true,
    "prh": {
      "rulePaths": ["prh.yml"]
    },
    "max-number-of-lines": false
  }
}
```

package.json

```
{
  "name": "document",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "textlint-rule-max-number-of-lines": "^1.0.2",
    "textlint-rule-max-ten": "^1.2.2",
    "textlint-rule-no-mix-dearu-desumasu": "^1.3.0",
    "textlint-rule-prh": "^2.0.0",
    "textlint-rule-spellcheck-tech-word": "^4.1.0"
  }
}
```

なお、textlint及びpackage.jsonに記載している各種ルールを、グローバルでインストールし、
texilintコマンドを実行すると正常にlint結果が表示される

**Comment by azu** [comment]
上の設定のプロジェクト作ってみました。
- https://github.com/azu/linter-textlint-issue-6

以下のコマンドで試せます。

```
git clone https://github.com/azu/linter-textlint-issue-6.git
cd linter-textlint-issue-6
npm i
atom .
# README.mdを見る
```

自分の環境だとこれで動きますね。。
- OS X 10.10.5
- Atom 1.0.19

以下のような表示が出ますね。

![img](https://monosnap.com/file/K8yh6auNRlD0A1zIMgNLZTd0byeCBr.png)

(プラグインは殆ど入れてない環境だけど、atomでプラグインの競合とかってあるのかな?)

**Comment by wate** [comment]
@azu 上記のリポジトリをcloneして、同じように試してみましたけど、
まったく反応してくれないですね・・・
他のプラグインも入れてるので、念のため他のプラグインを無効化して
再度、試してみましたけど、それでも状況は変わらないですね・・・

**Comment by 1000ch** [comment]
自分もEl Capitanですが、表示されません。初見だと **Atomそのもの** がEl Capitanだと怪しい感じがします。AtomとEl CapitanというよりAtomで使ってるChromiumとEl Capitan組み合わせという表現のほうが適切かも。
- 各種ショートカットが効かない
- 描画でたまにバグる
- `atom.project.rootDirectories`の値が参照出来る時と出来ない時がある

Atom本家にもEl Capitan関連で色々issueがあるようなので、本体の更新を待ちながら調査してみます。

**Comment by wate** [comment]
@1000ch なるほど、Atomそのものの問題ですか・・・
となると、もう、Atom自体の更新を待つしかしようがなさそうですね・・・

**Comment by azu** [comment]
Atom本体が怪しいのか…
それだと後は[Atom Beta Channel](https://atom.io/beta)で試すぐらいですね。
- http://blog.atom.io/2015/10/21/introducing-the-atom-beta-channel.html

**Comment by 1000ch** [comment]
`activate`ではなく`provideLinter`のときに、`atom.project.rootDirectories`参照すると大丈夫そうです。が、保存の度にlintのエンジンを初期化するのが微妙な気がしてるので、もう少し調査させてください。

**Comment by 1000ch** [comment]
@wate @azu 

プラグインのアクティベート時に`atom.project.rootDirectories`を参照できるときとできないときがあるので、`TextLintEngine`を都度初期化する方向で対応しました。設定ファイルを毎回探すのも微妙な気がしますが、設定の更新をOnFlyで反映できるのでコレでいい気もしてきました。

`v1.2.0`に更新して再度試してみてくださいー

**Comment by wate** [comment]
@1000ch `v1.2.0`に更新して動いてるのを確認できましたー！
